### ISSUE TITLE
Did not work for me

### ISSUE THREAD

**Issue by drisschelouati** [verve111/alfresco_cad_support#1]
Hi, as you explained i built the jar with ant and then dropped it in the alfresco/web-inf/lib folder. Then i installed qcad (Windows 10) and updated alfresco-global.properties accordons to your configuration. Dxf preview is a messy set of numbers and dwg preview doesnt work. I tested on Alfresco CE 5.0d.

**Comment by verve111** [comment]
On startup alfresco checks if the qcad is working and gives the result code. What's the result code?

**Comment by drisschelouati** [comment]
Where can i get  this result code? In alfresco.log?

**Comment by verve111** [comment]
Yes

**Comment by drisschelouati** [comment]
So this is an error code, you were right :+1: 

```
2016-05-29 21:28:53,693 ERROR [org.alfresco.repo.content.transform.RuntimeExecutableContentTransformerWorker] [localhost-startStop-1] Failed to start a runtime executable content transformer: 
Execution result: 
   os:         Windows 8
   command:    cmd /C "cd C:\QCAD\qcad.exe && dwg2pdf -h"
   succeeded:  false
   exit code:  1
   out:        
   err:        Nom de repertoire non valide.

```

it says my directory name is not valid. So maybe it didnt detect the executable at tomcat start. My installation directory for QCAD is C:\QCAD.

here is the corresponding line in my alfresco-global.properties : 

`dwg2pdf.root=C:\\QCAD\\qcad.exe`

Maybe i shouldnt use double slashes?

**Comment by verve111** [comment]
Please try dwg2pdf.root=C:/QCAD in your alfresco-global.properties

**Comment by drisschelouati** [comment]
didnt work either

**Comment by verve111** [comment]
if you have the same error, that means that you need to specify a correct path. 
You have "cd C:\QCAD\qcad.exe && dwg2pdf -h" command, cmd can not perform **cd** command on file name, there is should be a folder. Does it make sence?

**Comment by verve111** [comment]
I'm closing the issue. If the project still not working - please reopen the issue.
